# Generated by Django 5.0.3 on 2025-05-30 15:25

import backend_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('model_file', models.FileField(upload_to=backend_app.models.user_media_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=64)),
                ('table_used', models.CharField(max_length=64)),
                ('query', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response_text', models.TextField()),
                ('response_table', models.JSONField(blank=True, null=True)),
                ('graph_file', models.FileField(blank=True, null=True, upload_to=backend_app.models.user_media_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=backend_app.models.user_media_path)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('sql', 'SQL')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
