# Generated by Django 5.0.3 on 2025-05-30 18:07

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(max_length=512, upload_to=backend_app.models.user_media_path),
        ),
    ]
