# Generated by Django 5.0.3 on 2025-06-24 18:24

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_mlmodel_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresponse',
            name='response_table',
            field=models.FileField(blank=True, null=True, upload_to=backend_app.models.user_media_path),
        ),
    ]
